# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.4
maven_group = net.oxcodsnet.beltborne_lanterns
archives_name = beltborne_lanterns

# ===============================================
# Minecraft properties

minecraft_version = 1.21.9
neoform_version = 1.21.9-20250930.151910

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.134.0+1.21.9

neoforge_version = 21.9.16-beta

cloth_config_version=20.0.149
modmenu_version=16.0.0-rc.1

# ===============================================
mod_id=beltborne_lanterns
mod_name=Beltborne Lanterns
mod_description=Beltborne Lanterns - free hands, bright path!\n\nPress *B* while holding a lantern - it snaps onto your belt. Walk, jump, fight - the lantern sways with physics and casts light near you. Need it back in your hands - Press *B* again.
mod_authors=0xCoDSnet
mod_homepage=https://github.com/0xCoDSnet
mod_sources=https://github.com/0xCoDSnet/Beltborne-Lanterns
mod_license=Apache-2.0


# Optional integrations
# LambDynamicLights 4.x (for compileOnly usage)
lambdynamiclights_version=4.8.6+1.21.10
